(part "74HC595D"
    (packageRef "SOIC127P600X175-16N")
    (interface
        (port "1" (symbPinId 1) (portName "QB") (portType INOUT))
        (port "2" (symbPinId 2) (portName "QC") (portType INOUT))
        (port "3" (symbPinId 3) (portName "QD") (portType INOUT))
        (port "4" (symbPinId 4) (portName "QE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "QF") (portType INOUT))
        (port "6" (symbPinId 6) (portName "QG") (portType INOUT))
        (port "7" (symbPinId 7) (portName "QH_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "QH_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "%SCLR%") (portType INOUT))
        (port "11" (symbPinId 11) (portName "SCK") (portType INOUT))
        (port "12" (symbPinId 12) (portName "RCK") (portType INOUT))
        (port "13" (symbPinId 13) (portName "%G%") (portType INOUT))
        (port "14" (symbPinId 14) (portName "SI") (portType INOUT))
        (port "15" (symbPinId 15) (portName "QA") (portType INOUT))
        (port "16" (symbPinId 16) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "757-74HC595D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Toshiba/74HC595D?qs=7EBvPakHacViJoQmXKcnew%3D%3D")
    (property "Manufacturer_Name" "Toshiba")
    (property "Manufacturer_Part_Number" "74HC595D")
    (property "Description" "Shift Register Single 8-Bit Serial to Serial/Parallel 16-Pin SOIC T/R")
    (property "Datasheet_Link" "https://toshiba.semicon-storage.com/info/docget.jsp?did=36768&prodName=74HC595D")
    (property "symbolName1" "74HC595D")
)
