(part "PTSAHT120624V050"
    (packageRef "PTSAHT120624V050")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "504-PTSAHT120624V050")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bussmann-Eaton/PTSAHT120624V050?qs=aP1CjGhiNiFayTdxan91aA%3D%3D")
    (property "Manufacturer_Name" "Eaton")
    (property "Manufacturer_Part_Number" "PTSAHT120624V050")
    (property "Description" "Resettable Fuses - PPTC PTSAHT1206 0.5A, 24V")
    (property "Datasheet_Link" "https://www.eaton.com/content/dam/eaton/products/electronic-components/resources/data-sheet/eaton-ptsaht1206-automotive-surface-mount-resettable-fuse-data-sheet-elx1045-en.pdf")
    (property "symbolName1" "PTSAHT120624V050")
)
