(part "LCENA2520MKT2R2M0NK"
    (packageRef "LCENA2520")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "TAIYO YUDEN")
    (property "Manufacturer_Part_Number" "LCENA2520MKT2R2M0NK")
    (property "Description" "INDUCTORS[Wire-wound Metal Power Inductors MCOIL LCEN series for Automotive Body & Chassis and Infotainment]")
    (property "Datasheet_Link" "https://ds.yuden.co.jp/TYCOMPAS/or/detail?pn=LCENA2520MKT2R2M0NK")
    (property "symbolName1" "LCENA2520MKT2R2M0NK")
)
