(part "TPS25921ADR"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SS") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ENUV") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "%FLT%") (portType INOUT))
        (port "7" (symbPinId 7) (portName "ILIM") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OVP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS25921ADR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS25921ADR?qs=m%2F7bTylgptfvwfVPRm0ALQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS25921ADR")
    (property "Description" "18V, 1.6A, 90m eFuse with Adjustable +/-2% Accurate Current Limit")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tps25921a")
    (property "symbolName1" "TPS25921ADR")
)
